### ISSUE TITLE
Line breaks are added

### ISSUE THREAD

**Issue by franzarmas** [wp-cli/wp-config-transformer#27]
It is normal that when running wp-config-transformer line breaks are added throughout the wp-config.php file ???

Why?

![img](https://i.imgur.com/86Pypx1.png)

**Comment by Ryvix** [comment]
Hi, did you figure out what the cause was for this? It happened to me too but now I'm having trouble reproducing it again and I can't figure out what's going on.

**Comment by franzarmas** [comment]
@Ryvix  Yes friend, I read in your documentation that this is the expected behavior for Windows operating systems.

In Linux if it works correctly, it does not add additional newlines.

**Comment by onetrev** [comment]
@franzarmas I am using Linux and it is adding the line breaks for me -- I'm using Ubuntu 20.04 using WSL2. I'm performing the operation in my WSL instance though, so the Windows file system isn't involved.

The command I'm running is: `wp config set WP_DEBUG true --raw`. It's adding a line break every other line. Any ideas what the issue might be?
