### ISSUE TITLE
Adapt testing to use the central `wp-cli/wp-cli-tests` package

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-config-transformer#30]
As it is part of the `wp-cli-bundle`, this package should be adapted to make use of the central `wp-cli/wp-cli-tests` package. This will allow for its testing infrastructure to be centrally managed and kept up-to-date along with the rest of the bundle repos.

**Comment by danielbachhuber** [comment]
Looks like this was done with https://github.com/wp-cli/wp-config-transformer/pull/36
